"""Typed AGENTS.md rules: one .duckterm-rules.json per folder is the source of
truth; AGENTS.md is rendered from it and carries a generated banner.

Design: docs/agents-template.md. Lifecycle: machine-proposed rules land as
"candidate"; a human promotes to "active" or demotes to "rejected". Rejected
rules stay as tombstones so the suggest loop never re-proposes the same rule
from the same corrections. Only active rules render into AGENTS.md.
"""

import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path

RULES_FILENAME = ".duckterm-rules.json"
AGENTS_FILENAME = "AGENTS.md"
GENERATED_BANNER = (
    "<!-- generated by DuckTerm from .duckterm-rules.json — edit rules in the "
    "dashboard (AGENTS.md button); hand edits here are overwritten on save -->"
)

STATUSES = ("active", "candidate", "rejected")
SOURCES = ("manual", "correction", "digest", "retro")


@dataclass
class RuleBlock:
    id: str
    text: str
    scope: str = "all"  # "all" | runtime | "runtime/model" (e.g. "claude-code/fable-5")
    status: str = "candidate"
    source: str = "manual"
    evidence: int = 1
    added: str = ""  # ISO date
    heading: str = ""  # optional markdown section the rule renders under
    note: str = ""  # reviewer note, e.g. why a rule was rejected

    def matches(self, runtime: str, model: str | None = None) -> bool:
        """Does this rule apply to a session on `runtime` (+ optional model)?
        Scope "claude-code" matches every claude-code session; scope
        "claude-code/fable-5" matches only when the model is known and its id
        contains the fragment (model ids are long: "claude-fable-5")."""
        if self.scope == "all":
            return True
        want_runtime, _, want_model = self.scope.partition("/")
        if want_runtime != runtime:
            return False
        if not want_model:
            return True
        return bool(model) and want_model in str(model)


def rule_id(text: str) -> str:
    """Deterministic kebab-case id from rule text — the dedupe key for
    machine-proposed rules (same correction distilled twice -> same id)."""
    words = re.findall(r"[a-z0-9]+", text.lower())
    return "-".join(words[:6]) or "rule"


def load_rules(directory: Path) -> list[RuleBlock]:
    path = directory / RULES_FILENAME
    if not path.is_file():
        return []
    known = set(RuleBlock.__dataclass_fields__)
    raw = json.loads(path.read_text())
    out: list[RuleBlock] = []
    for entry in raw.get("rules", []):
        if not isinstance(entry, dict) or not entry.get("id") or not entry.get("text"):
            continue
        out.append(RuleBlock(**{k: v for k, v in entry.items() if k in known}))
    return out


def save_rules(directory: Path, rules: list[RuleBlock]) -> None:
    """Write rules.json AND render AGENTS.md next to it — the two files never
    drift because this is the only writer."""
    path = directory / RULES_FILENAME
    path.write_text(json.dumps({"rules": [asdict(r) for r in rules]}, indent=2) + "\n")
    (directory / AGENTS_FILENAME).write_text(render_agents_md(rules))


def render_agents_md(rules: list[RuleBlock]) -> str:
    """AGENTS.md content: active rules only, grouped by heading, scope-labeled
    inline so an agent reading the raw file knows which rules are its own."""
    lines = [GENERATED_BANNER, "", "# AGENTS.md", ""]
    active = [r for r in rules if r.status == "active"]
    scoped_note = any(r.scope != "all" for r in active)
    if scoped_note:
        lines += [
            "Rules labeled with a scope apply only to that agent runtime (or "
            "runtime/model); skip rules scoped to a runtime that isn't you.",
            "",
        ]
    current_heading: str | None = None
    for r in active:
        if r.heading != (current_heading or "") and r.heading:
            lines += [f"## {r.heading}", ""]
        current_heading = r.heading
        label = "" if r.scope == "all" else f" *({r.scope} only)*"
        body = r.text.strip()
        first, *rest = body.splitlines()
        lines.append(f"- {first}{label}")
        lines += [f"  {ln.strip()}" for ln in rest]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def merge_candidates(existing: list[RuleBlock], proposed: list[RuleBlock]) -> list[RuleBlock]:
    """Append proposals not already present under ANY status — a rejected
    tombstone blocks re-proposal. Growing evidence on an existing candidate
    with the same id is the one mutation allowed."""
    seen = {r.id: r for r in existing}
    out = list(existing)
    for p in proposed:
        prior = seen.get(p.id)
        if prior is None:
            p.status = "candidate"
            out.append(p)
            seen[p.id] = p
        elif prior.status == "candidate":
            prior.evidence = max(prior.evidence, p.evidence)
    return out


def infer_scope(runtimes: set[str], models: set[str]) -> str:
    """Scope for a machine-proposed rule from where its evidence came:
    one runtime+one model -> "runtime/model-fragment"; one runtime -> runtime;
    mixed -> "all"."""
    if len(runtimes) != 1:
        return "all"
    runtime = next(iter(runtimes))
    real_models = {m for m in models if m}
    if len(real_models) == 1:
        model = next(iter(real_models))
        # Store the distinctive fragment ("fable-5" from "claude-fable-5") so
        # matching survives dated model-id suffixes.
        fragment = re.sub(r"^claude-", "", model)
        return f"{runtime}/{fragment}"
    return runtime
