import { act, cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { api, BroadcastStatus, OracleExchange } from "./api";
import { BroadcastDelivery } from "./BroadcastDelivery";
vi.mock("./api", () => ({ api: { broadcastStatus: vi.fn(), cancelBroadcast: vi.fn() } }));
const dispatch: NonNullable<OracleExchange["dispatch"]> = { request_key: "send-1", delivery_key: "folder:identity:send-1", priority: true, target: { kind: "folder", id: "a" }, label: "a", recipients: [{ session_id: "one", name: "review-dev", message_id: "m1", status: "queued", answer: "Saved reply" }, { session_id: "two", name: "qa", message_id: "m2", status: "queued", answer: null }] };
const status = (first: BroadcastStatus["recipients"][number]["status"] = "delivered", second: BroadcastStatus["recipients"][number]["status"] = "inbox only"): BroadcastStatus => ({ request_key: dispatch.delivery_key!, priority: true, recipients: dispatch.recipients.map((r, i) => ({ ...r, status: i ? second : first })) });
afterEach(() => { cleanup(); vi.useRealTimers(); vi.resetAllMocks(); Object.defineProperty(document, "visibilityState", { configurable: true, value: "visible" }); });
it("shows server statuses and keeps acknowledgments on confirmed cancellation", async () => {
  vi.mocked(api.broadcastStatus).mockResolvedValue(status("acknowledged"));
  vi.mocked(api.cancelBroadcast).mockResolvedValue(status("acknowledged", "cancelled"));
  render(<BroadcastDelivery dispatch={dispatch} active />);
  await screen.findByText("acknowledged");
  expect(screen.getByText("inbox only")).toBeVisible();
  fireEvent.click(screen.getByRole("button", { name: "Cancel broadcast" }));
  const dialog = screen.getByRole("dialog");
  expect(dialog).toHaveTextContent("cannot retract text");
  await act(async () => { fireEvent.click(within(dialog).getByRole("button", { name: "Cancel broadcast" })); });
  expect(api.cancelBroadcast).toHaveBeenCalledWith(dispatch.delivery_key);
  expect(screen.getByText("acknowledged")).toBeVisible();
  expect(screen.getByText("cancelled")).toBeVisible();
  expect(screen.queryByRole("button", { name: "Cancel broadcast" })).not.toBeInTheDocument();
});
it("retired status keeps saved reply and last known states without claiming new delivery", async () => {
  vi.useFakeTimers();
  vi.mocked(api.broadcastStatus).mockRejectedValue(Object.assign(new Error("retired"), { status: 404 }));
  render(<BroadcastDelivery dispatch={{ ...dispatch, delivery_status: { m1: "delivered", m2: "inbox only" } }} active />);
  await act(async () => {});
  expect(screen.getByText("delivered")).toBeVisible();
  expect(screen.getByText("Saved reply")).toBeVisible();
  expect(screen.getByRole("status")).toHaveTextContent("no longer available");
  expect(screen.getByRole("button", { name: "Cancel broadcast" })).toBeDisabled();
  await act(async () => { vi.advanceTimersByTime(15000); });
  expect(api.broadcastStatus).toHaveBeenCalledTimes(1);
});
it("pauses hidden polling and an old read cannot undo cancellation", async () => {
  vi.useFakeTimers();
  let finish!: (value: BroadcastStatus) => void;
  vi.mocked(api.broadcastStatus).mockResolvedValueOnce(status()).mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })).mockResolvedValue(status("cancelled", "cancelled"));
  vi.mocked(api.cancelBroadcast).mockResolvedValue(status("cancelled", "cancelled"));
  const view = render(<BroadcastDelivery dispatch={dispatch} active />);
  await act(async () => {});
  await act(async () => { vi.advanceTimersByTime(3000); });
  fireEvent.click(screen.getByRole("button", { name: "Cancel broadcast" }));
  await act(async () => { fireEvent.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Cancel broadcast" })); });
  await act(async () => { finish(status()); });
  expect(screen.queryByText("delivered")).not.toBeInTheDocument();
  expect(screen.getAllByText("cancelled")).toHaveLength(2);
  view.rerender(<BroadcastDelivery dispatch={dispatch} active={false} />);
  await act(async () => { vi.advanceTimersByTime(15000); });
  expect(api.broadcastStatus).toHaveBeenCalledTimes(2);
  Object.defineProperty(document, "visibilityState", { configurable: true, value: "hidden" });
  view.rerender(<BroadcastDelivery dispatch={dispatch} active />);
  await act(async () => { vi.advanceTimersByTime(15000); });
  expect(api.broadcastStatus).toHaveBeenCalledTimes(2);
  Object.defineProperty(document, "visibilityState", { configurable: true, value: "visible" });
  await act(async () => { document.dispatchEvent(new Event("visibilitychange")); });
  expect(api.broadcastStatus).toHaveBeenCalledTimes(3);
});
it("failed cancellation leaves prior statuses and an actionable error", async () => {
  vi.mocked(api.broadcastStatus).mockResolvedValue(status());
  vi.mocked(api.cancelBroadcast).mockRejectedValue(new Error("offline"));
  render(<BroadcastDelivery dispatch={dispatch} active />);
  await screen.findByText("delivered");
  fireEvent.click(screen.getByRole("button", { name: "Cancel broadcast" }));
  await act(async () => { fireEvent.click(within(screen.getByRole("dialog")).getByRole("button", { name: "Cancel broadcast" })); });
  expect(screen.getByRole("alert")).toHaveTextContent("Couldn’t confirm cancellation");
  expect(screen.getByText("delivered")).toBeVisible();
});
