"""oh-my-zsh prompt themes for launched sessions.

The user's ~/.zshrc hardcodes ZSH_THEME, so exporting the variable into the
agent's environment does nothing — .zshrc overwrites it. Instead we point
ZDOTDIR at a generated wrapper that sources the real ~/.zshrc first and then
re-sources the chosen theme file on top.
"""

from __future__ import annotations

from pathlib import Path

from duckterm.helpers import paths

_THEME_DIRS = (".oh-my-zsh/themes", ".oh-my-zsh/custom/themes")


def list_themes() -> list[str]:
    """Theme names from ~/.oh-my-zsh (stock + custom). Empty if no oh-my-zsh."""
    names: set[str] = set()
    for rel in _THEME_DIRS:
        d = Path.home() / rel
        if d.is_dir():
            names.update(p.stem for p in d.glob("*.zsh-theme"))
    return sorted(names)


def theme_env(name: str) -> dict[str, str]:
    """Env vars that make new zsh shells use `name` as the prompt theme.

    Writes (or refreshes) the ZDOTDIR wrapper for the theme. Raises ValueError
    for a name that isn't an installed theme — which also keeps arbitrary
    strings out of the filesystem paths below.
    """
    if name not in list_themes():
        raise ValueError(f"unknown zsh theme: {name}")
    zdot = paths.home() / "zsh-themes" / name
    zdot.mkdir(parents=True, exist_ok=True)
    # Login shells read .zprofile from ZDOTDIR, not $HOME — pass it through so
    # the wrapper doesn't silently drop the user's PATH setup.
    (zdot / ".zprofile").write_text('[ -f "$HOME/.zprofile" ] && source "$HOME/.zprofile"\n')
    (zdot / ".zshenv").write_text('[ -f "$HOME/.zshenv" ] && source "$HOME/.zshenv"\n')
    (zdot / ".zshrc").write_text(
        "# Generated by Duckterm — do not edit. Runs your real zshrc, then\n"
        "# swaps the prompt theme for this session only.\n"
        "# Nested shells the agent spawns get the normal config again:\n"
        'export ZDOTDIR="$HOME"\n'
        '[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"\n'
        f'ZSH_THEME="{name}"\n'
        f'for _dt_f in "$ZSH/custom/themes/{name}.zsh-theme" "$ZSH/themes/{name}.zsh-theme"; do\n'
        '  if [ -f "$_dt_f" ]; then source "$_dt_f"; break; fi\n'
        "done\n"
        "unset _dt_f\n"
    )
    return {"ZDOTDIR": str(zdot)}
